version: '3.8'

services:
  eduprime_db:
    image: timescale/timescaledb:latest-pg16
    container_name: eduprime_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Recife
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - eduprime_db_data:/var/lib/postgresql/data
      - ./custom-postgresql.conf:/etc/postgresql/postgresql.conf
    entrypoint: >
      sh -c "apk add --no-cache tzdata &&
             cp /usr/share/zoneinfo/America/Recife /etc/localtime &&
             echo 'America/Recife' > /etc/timezone &&
             echo 'shared_preload_libraries=timescaledb' >> /etc/postgresql/postgresql.conf &&
             exec docker-entrypoint.sh postgres"
volumes:
  eduprime_db_data:
