GET http://localhost:3000/books
content-type: application/json

###

POST http://localhost:3000/books
content-type: application/json

{
    "title": "Teste",
    "author": "Hermes", 
    "description": "Teste de descrição"
}